apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{  .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  schedule: "0 * * * *"  # Runs every hour
  concurrencyPolicy: Forbid

  # Job history limit in the Kubernetes cluster
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 5

  jobTemplate:
    metadata:
      name: {{ .Chart.Name }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/name: {{  .Chart.Name }}
            app.kubernetes.io/version: {{ .Chart.AppVersion }}
            helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: harbor-credentials

          volumes:
            - name: etcd-certs
              secret:
                secretName: etcd-certs
            - name: backup-dir
              persistentVolumeClaim:
                claimName: {{ .Chart.Name }}

          securityContext:
            fsGroup: 1000

          initContainers:
          - name: volume-permission
            image: busybox
            command: ["sh", "-c", "chown -R 1000:1000 /backup"]
            volumeMounts:
            - name: backup-dir
              mountPath: /backup
            securityContext:
              runAsNonRoot: false
              runAsUser: 0

          containers:
          - name: etcd-backup
            image: registry.hibbard.dev/homelab/{{ .Chart.Name }}:main
            volumeMounts:
              - name: etcd-certs
                mountPath: /var/run/secrets/etcd-certs
                readOnly: true
              - name: backup-dir
                mountPath: /backup

            env:
              - name: ETCD_HOST
                valueFrom:
                  configMapKeyRef:
                    name: etcd-host
                    key: etcd-host

            resources:
              requests:
                cpu: 200m
                memory: 100Mi
              limits:
                cpu: 500m
                memory: 200Mi

            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true